## Load Credit Card Balance

In [3]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
import os
import zipfile
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion, make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from pandas.plotting import scatter_matrix
import warnings
warnings.filterwarnings('ignore')

def load_data(in_path, name):
    df = pd.read_csv(in_path)
    print(f"{name}: shape is {df.shape}")
    print(df.info())
    display(df.head(5))
    return df

DATA_DIR = "./Data"
datasets={}  # lets store the datasets in a dictionary so we can keep track of them easily
ds_name = 'credit_card_balance'
datasets[ds_name] = load_data(os.path.join(DATA_DIR, f'{ds_name}.csv'), ds_name)

datasets['credit_card_balance'].shape

credit_card_balance: shape is (3840312, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB
None

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

(3840312, 23)

In [4]:
# function to display amount of missing data from dataframe columns
def missing_data(data):
    total = data.isnull().sum().sort_values(ascending = False)
    percent = (data.isnull().sum()/data.isnull().count()*100).sort_values(ascending = False)
    return pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])

# Class to summarize the features specified into min, max, mean, count, sum, median, and var
class FeatureSummarizer(BaseEstimator, TransformerMixin):
    def __init__(self, features=None): # no *args or **kargs
        self.features = features
        self.agg_ops = ["min", "max", "count", "sum", "median", "mean", "var"]

    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        keys = list(set(X.columns) - set(self.features))
        
        result = X.groupby(keys, as_index=False) \
                  .agg({ft:self.agg_ops for ft in self.features}) 
        result.columns = result.columns.map(lambda ct: '_'.join([x for x in ct if x != '']))
        
        return result 
    

def runFeatureSummarizer(df, features):
    print(f"df.shape: {df.shape}\n")
    print(f"Aggregated Features:\ndf[{features}][0:5]: \n{df[features][0:5]}")
    pipeline = make_pipeline(FeatureSummarizer(features))
    return(pipeline.fit_transform(df))

## Creating Summarized Dataset for Credit Card Balance

In [5]:
df_ccb = datasets['credit_card_balance']
df_ccb_dummies= pd.get_dummies(data=df_ccb,
                        columns=['NAME_CONTRACT_STATUS'])
id_cols = ['SK_ID_PREV',
           'SK_ID_CURR']
df_ccb_col_list = list(set(df_ccb_dummies.columns) - set(id_cols))
df_ccb_summ = runFeatureSummarizer(df_ccb_dummies, df_ccb_col_list)

df.shape: (3840312, 29)

Aggregated Features:
df[['CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'AMT_BALANCE', 'NAME_CONTRACT_STATUS_Sent proposal', 'NAME_CONTRACT_STATUS_Completed', 'SK_DPD', 'NAME_CONTRACT_STATUS_Approved', 'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS_Active', 'AMT_DRAWINGS_CURRENT', 'AMT_TOTAL_RECEIVABLE', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_PAYMENT_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_DRAWINGS_ATM_CURRENT', 'MONTHS_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'SK_DPD_DEF', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'NAME_CONTRACT_STATUS_Signed', 'NAME_CONTRACT_STATUS_Refused', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECIVABLE', 'NAME_CONTRACT_STATUS_Demand', 'AMT_INST_MIN_REGULARITY']][0:5]:
   CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_POS_CURRENT  AMT_BALANCE  \
0                     1                       1.0       56.970
1                     1                       0.0    63975.555
2                     0                       0.0    31815.225
3                     1                       0.0   236572.110
4                     1                       1.0   453919.455

   NAME_CONTRACT_STATUS_Sent proposal  NAME_CONTRACT_STATUS_Completed  SK_DPD  \
0                                   0                               0       0
1                                   0                               0       0
2                                   0                               0       0
3                                   0                               0       0
4                                   0                               0       0

   NAME_CONTRACT_STATUS_Approved  CNT_INSTALMENT_MATURE_CUM  \
0                              0                       35.0
1                              0                       69.0
2                              0                       30.0
3                              0                       10.0
4                              0                      101.0

   NAME_CONTRACT_STATUS_Active  AMT_DRAWINGS_CURRENT  ...  \
0                            1                 877.5  ...
1                            1                2250.0  ...
2                            1                   0.0  ...
3                            1                2250.0  ...
4                            1               11547.0  ...

   AMT_CREDIT_LIMIT_ACTUAL  SK_DPD_DEF  CNT_DRAWINGS_ATM_CURRENT  \
0                   135000           0                       0.0
1                    45000           0                       1.0
2                   450000           0                       0.0
3                   225000           0                       1.0
4                   450000           0                       0.0

   CNT_DRAWINGS_OTHER_CURRENT  NAME_CONTRACT_STATUS_Signed  \
0                         0.0                            0
1                         0.0                            0
2                         0.0                            0
3                         0.0                            0
4                         0.0                            0

   NAME_CONTRACT_STATUS_Refused  AMT_PAYMENT_TOTAL_CURRENT  AMT_RECIVABLE  \
0                             0                     1800.0          0.000
1                             0                     2250.0      64875.555
2                             0                     2250.0      31460.085
3                             0                    11925.0     233048.970
4                             0                    27000.0     453919.455

   NAME_CONTRACT_STATUS_Demand  AMT_INST_MIN_REGULARITY
0                            0                 1700.325
1                            0                 2250.000
2                            0                 2250.000
3                            0                11795.760
4                            0                22924.890

[5 rows x 27 columns]

## EDA on credit_card_balance.csv

### 1) A data dictionary of the raw features (test description; data type: numerical, list, etc.)

In [6]:
credit_card_balance_csv = pd.read_csv("CreditCardBalance.csv")

In [7]:
credit_card_balance_csv

,Attribute,DataType,Description
0,SK_ID_PREV,NUMBER,ID of previous credit in Home credit related t...
1,SK_ID_CURR,NUMBER,ID of loan in main sample
2,MONTHS_BALANCE,NUMBER,Month of balance relative to application date ...
3,AMT_BALANCE,NUMBER,Balance during the month of previous credit
4,AMT_CREDIT_LIMIT_ACTUAL,NUMBER,Credit card limit during the month of the prev...
5,AMT_DRAWINGS_ATM_CURRENT,NUMBER,Amount drawing at ATM during the month of the ...
6,AMT_DRAWINGS_CURRENT,NUMBER,Amount drawing during the month of the previou...
7,AMT_DRAWINGS_OTHER_CURRENT,NUMBER,Amount of other drawings during the month of t...
8,AMT_DRAWINGS_POS_CURRENT,NUMBER,Amount drawing or buying goods during the mont...
9,AMT_INST_MIN_REGULARITY,NUMBER,Minimal installment for this month of the prev...
10,AMT_PAYMENT_CURRENT,NUMBER,Amount client paid during the month on the pre...
11,AMT_PAYMENT_TOTAL_CURRENT,NUMBER,How much did the client pay during the month i...
12,AMT_RECEIVABLE_PRINCIPAL,NUMBER,Amount receivable for principal on the previou...
13,AMT_RECIVABLE,NUMBER,Amount receivable on the previous credit
14,AMT_TOTAL_RECEIVABLE,NUMBER,Total amount receivable on the previous credit
15,CNT_DRAWINGS_ATM_CURRENT,NUMBER,Number of drawings at ATM during this month on...
16,CNT_DRAWINGS_CURRENT,NUMBER,Number of drawings during this month on the pr...
17,CNT_DRAWINGS_OTHER_CURRENT,NUMBER,Number of other drawings during this month on ...
18,CNT_DRAWINGS_POS_CURRENT,NUMBER,Number of drawings for goods during this month...
19,CNT_INSTALMENT_MATURE_CUM,NUMBER,Number of paid installments on the previous cr...
20,NAME_CONTRACT_STATUS,STRING,Contract status on the previous credit
21,SK_DPD,NUMBER,DPD (Days past due) during the month on the pr...
22,SK_DPD_DEF,NUMBER,DPD (Days past due) during the month with tole...

## 2) Dataset size for CREDIT CARD BALANCE (rows columns, train, test, validation)

In [8]:
size = datasets['credit_card_balance'].shape
print("The Credit Card Balance dataset before summarized consists of " + str(size[0]) +" rows.")
print("The Credit Card Balance dataset before summarized consists of " + str(size[1]) +" columns.")

The Credit Card Balance dataset before summarized consists of 3840312 rows.
The Credit Card Balance dataset before summarized consists of 23 columns.

In [9]:
size = df_ccb_summ.shape
print("The Credit Card Balance dataset after summarized consists of " + str(size[0]) +" rows.")
print("The Credit Card Balance dataset after summarized consists of " + str(size[1]) +" columns.")

The Credit Card Balance dataset after summarized consists of 104307 rows.
The Credit Card Balance dataset after summarized consists of 191 columns.

## Train dataset joined on SK_ID_CURR with summarized Credit Card Balance

In [10]:
ds_name = 'application_train'
datasets[ds_name] = load_data(os.path.join(DATA_DIR, f'{ds_name}.csv'), ds_name)
df_curr_target = datasets[ds_name][["SK_ID_CURR","TARGET"]]
df_summarized_joined_train_ccb = df_ccb_summ.join(datasets['application_train'].set_index('SK_ID_CURR'), on='SK_ID_CURR')
df_summarized_joined_train_ccb.shape

application_train: shape is (307511, 122)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB
None

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

(104307, 312)

## 3) Summary statistics for CREDIT CARD BALANCE

In [11]:
def EDA(df, features, idCols):

    features = list(set(df.columns) - set(id_cols))
    num_features = list(df[features].select_dtypes(include=['int64', 'float64']).columns)
    cat_features = list(df[features].select_dtypes(include=['object', 'bool']).columns)

    print(f"ID columns: {list(id_cols)}")
    print(f"Feature columns: {features}")
    print('')
    print(f"Missing data: {missing_data(df[features])}")
    print('--------')
    print(f"# of numerical features: {len(num_features)}")
    print(f"Numerical features: {num_features}")
    print('')
    print(df[features].describe())
    print('--------')
    print(f"# of categorical features: {len(cat_features)}")
    print(f"Categorical features: {cat_features}")
    print('')
    print(df[cat_features].describe(include='all'))
    print(df[cat_features].apply(lambda col: col.unique()))
    print('--------')

def AggregatedEDA(df, features, idCols):
    print('Aggregated Features:')
    df = runFeatureSummarizer(df, features)
    features = list(set(df.columns) - set(id_cols))
    print('--------')
    print('Aggregated Features:')
    print('\n'.join(map(str, sorted(features))))
    print('')
    print('Aggregated bureau:')
    print('')
    print(df[features].describe().T)

## EDA and Aggregated EDA on Credit Card Balance Dataset

In [12]:
id_cols = ['SK_ID_PREV',
           'SK_ID_CURR']
EDA(df_ccb, df_ccb_col_list, id_cols)
AggregatedEDA(df_ccb_dummies, df_ccb_col_list, id_cols)

ID columns: ['SK_ID_PREV', 'SK_ID_CURR']
Feature columns: ['CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'AMT_BALANCE', 'SK_DPD', 'CNT_INSTALMENT_MATURE_CUM', 'AMT_DRAWINGS_CURRENT', 'AMT_TOTAL_RECEIVABLE', 'AMT_DRAWINGS_OTHER_CURRENT', 'NAME_CONTRACT_STATUS', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_PAYMENT_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_DRAWINGS_ATM_CURRENT', 'MONTHS_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'SK_DPD_DEF', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECIVABLE', 'AMT_INST_MIN_REGULARITY']

Missing data:                              Total    Percent
AMT_PAYMENT_CURRENT         767988  19.998063
AMT_DRAWINGS_OTHER_CURRENT  749816  19.524872
CNT_DRAWINGS_OTHER_CURRENT  749816  19.524872
CNT_DRAWINGS_ATM_CURRENT    749816  19.524872
AMT_DRAWINGS_ATM_CURRENT    749816  19.524872
CNT_DRAWINGS_POS_CURRENT    749816  19.524872
AMT_DRAWINGS_POS_CURRENT    749816  19.524872
AMT_INST_MIN_REGULARITY     305236   7.948208
CNT_INSTALMENT_MATURE_CUM   305236   7.948208
NAME_CONTRACT_STATUS             0   0.000000
AMT_TOTAL_RECEIVABLE             0   0.000000
AMT_DRAWINGS_CURRENT             0   0.000000
AMT_RECEIVABLE_PRINCIPAL         0   0.000000
MONTHS_BALANCE                   0   0.000000
AMT_CREDIT_LIMIT_ACTUAL          0   0.000000
SK_DPD_DEF                       0   0.000000
SK_DPD                           0   0.000000
AMT_BALANCE                      0   0.000000
AMT_PAYMENT_TOTAL_CURRENT        0   0.000000
AMT_RECIVABLE                    0   0.000000
CNT_DRAWINGS_CURRENT             0   0.000000
--------
# of numerical features: 20
Numerical features: ['CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'AMT_BALANCE', 'SK_DPD', 'CNT_INSTALMENT_MATURE_CUM', 'AMT_DRAWINGS_CURRENT', 'AMT_TOTAL_RECEIVABLE', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_PAYMENT_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_DRAWINGS_ATM_CURRENT', 'MONTHS_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'SK_DPD_DEF', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECIVABLE', 'AMT_INST_MIN_REGULARITY']

       CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_POS_CURRENT   AMT_BALANCE  \
count          3.840312e+06              3.090496e+06  3.840312e+06
mean           7.031439e-01              5.594791e-01  5.830016e+04
std            3.190347e+00              3.240649e+00  1.063070e+05
min            0.000000e+00              0.000000e+00 -4.202502e+05
25%            0.000000e+00              0.000000e+00  0.000000e+00
50%            0.000000e+00              0.000000e+00  0.000000e+00
75%            0.000000e+00              0.000000e+00  8.904669e+04
max            1.650000e+02              1.650000e+02  1.505902e+06

             SK_DPD  CNT_INSTALMENT_MATURE_CUM  AMT_DRAWINGS_CURRENT  \
count  3.840312e+06               3.535076e+06          3.840312e+06
mean   9.283667e+00               2.082508e+01          7.433388e+03
std    9.751570e+01               2.005149e+01          3.384608e+04
min    0.000000e+00               0.000000e+00         -6.211620e+03
25%    0.000000e+00               4.000000e+00          0.000000e+00
50%    0.000000e+00               1.500000e+01          0.000000e+00
75%    0.000000e+00               3.200000e+01          0.000000e+00
max    3.260000e+03               1.200000e+02          2.287098e+06

       AMT_TOTAL_RECEIVABLE  AMT_DRAWINGS_OTHER_CURRENT  \
count          3.840312e+06                3.090496e+06
mean           5.809829e+04                2.881696e+02
std            1.059718e+05                8.201989e+03
min           -4.202502e+05                0.000000e+00
25%            0.000000e+00                0.000000e+00
50%            0.000000e+00                0.000000e+00
75%            8.891451e+04                0.000000e+00
max            1.493338e+06                1.529847e+06

       AMT_DRAWINGS_POS_CURRENT  AMT_PAYMENT_CURRENT  \
count              3.090496e+06         3.072324e+06
mean               2.968805e+03         1.028054e+04
std                2.079689e+04         3.607808e+04
min                0.000000e+00         0.000000e+00
25%                0.000000e+00         1.523700e+02
50%                0.000000e+00         2.702700e+03
75%                0.000000e+00         9.000000e+03
max                2.239274e+06         4.289207e+06

       AMT_RECEIVABLE_PRINCIPAL  AMT_DRAWINGS_ATM_CURRENT  MONTHS_BALANCE  \
count              3.840312e+06              3.090496e+06    3.840312e+06
mean               5.596588e+04              5.961325e+03   -3.452192e+01
std                1.025336e+05              2.822569e+04    2.666775e+01
min               -4.233058e+05             -6.827310e+03   -9.600000e+01
25%                0.000000e+00              0.000000e+00   -5.500000e+01
50%                0.000000e+00              0.000000e+00   -2.800000e+01
75%                8.535924e+04              0.000000e+00   -1.100000e+01
max                1.472317e+06              2.115000e+06   -1.000000e+00

       AMT_CREDIT_LIMIT_ACTUAL    SK_DPD_DEF  CNT_DRAWINGS_ATM_CURRENT  \
count             3.840312e+06  3.840312e+06              3.090496e+06
mean              1.538080e+05  3.316220e-01              3.094490e-01
std               1.651457e+05  2.147923e+01              1.100401e+00
min               0.000000e+00  0.000000e+00              0.000000e+00
25%               4.500000e+04  0.000000e+00              0.000000e+00
50%               1.125000e+05  0.000000e+00              0.000000e+00
75%               1.800000e+05  0.000000e+00              0.000000e+00
max               1.350000e+06  3.260000e+03              5.100000e+01

       CNT_DRAWINGS_OTHER_CURRENT  AMT_PAYMENT_TOTAL_CURRENT  AMT_RECIVABLE  \
count                3.090496e+06               3.840312e+06   3.840312e+06
mean                 4.812496e-03               7.588857e+03   5.808881e+04
std                  8.263861e-02               3.200599e+04   1.059654e+05
min                  0.000000e+00               0.000000e+00  -4.202502e+05
25%                  0.000000e+00               0.000000e+00   0.000000e+00
50%                  0.000000e+00               0.000000e+00   0.000000e+00
75%                  0.000000e+00               6.750000e+03   8.889949e+04
max                  1.200000e+01               4.278316e+06   1.493338e+06

       AMT_INST_MIN_REGULARITY
count             3.535076e+06
mean              3.540204e+03
std               5.600154e+03
min               0.000000e+00
25%               0.000000e+00
50%               0.000000e+00
75%               6.633911e+03
max               2.028820e+05
--------
# of categorical features: 1
Categorical features: ['NAME_CONTRACT_STATUS']

       NAME_CONTRACT_STATUS
count               3840312
unique                    7
top                  Active
freq                3698436
  NAME_CONTRACT_STATUS
0               Active
1            Completed
2               Demand
3               Signed
4        Sent proposal
5              Refused
6             Approved
--------
Aggregated Features:
df.shape: (3840312, 29)

Aggregated Features:
df[['CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'AMT_BALANCE', 'NAME_CONTRACT_STATUS_Sent proposal', 'NAME_CONTRACT_STATUS_Completed', 'SK_DPD', 'NAME_CONTRACT_STATUS_Approved', 'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS_Active', 'AMT_DRAWINGS_CURRENT', 'AMT_TOTAL_RECEIVABLE', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_PAYMENT_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_DRAWINGS_ATM_CURRENT', 'MONTHS_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'SK_DPD_DEF', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'NAME_CONTRACT_STATUS_Signed', 'NAME_CONTRACT_STATUS_Refused', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECIVABLE', 'NAME_CONTRACT_STATUS_Demand', 'AMT_INST_MIN_REGULARITY']][0:5]:
   CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_POS_CURRENT  AMT_BALANCE  \
0                     1                       1.0       56.970
1                     1                       0.0    63975.555
2                     0                       0.0    31815.225
3                     1                       0.0   236572.110
4                     1                       1.0   453919.455

   NAME_CONTRACT_STATUS_Sent proposal  NAME_CONTRACT_STATUS_Completed  SK_DPD  \
0                                   0                               0       0
1                                   0                               0       0
2                                   0                               0       0
3                                   0                               0       0
4                                   0                               0       0

   NAME_CONTRACT_STATUS_Approved  CNT_INSTALMENT_MATURE_CUM  \
0                              0                       35.0
1                              0                       69.0
2                              0                       30.0
3                              0                       10.0
4                              0                      101.0

   NAME_CONTRACT_STATUS_Active  AMT_DRAWINGS_CURRENT  ...  \
0                            1                 877.5  ...
1                            1                2250.0  ...
2                            1                   0.0  ...
3                            1                2250.0  ...
4                            1               11547.0  ...

   AMT_CREDIT_LIMIT_ACTUAL  SK_DPD_DEF  CNT_DRAWINGS_ATM_CURRENT  \
0                   135000           0                       0.0
1                    45000           0                       1.0
2                   450000           0                       0.0
3                   225000           0                       1.0
4                   450000           0                       0.0

   CNT_DRAWINGS_OTHER_CURRENT  NAME_CONTRACT_STATUS_Signed  \
0                         0.0                            0
1                         0.0                            0
2                         0.0                            0
3                         0.0                            0
4                         0.0                            0

   NAME_CONTRACT_STATUS_Refused  AMT_PAYMENT_TOTAL_CURRENT  AMT_RECIVABLE  \
0                             0                     1800.0          0.000
1                             0                     2250.0      64875.555
2                             0                     2250.0      31460.085
3                             0                    11925.0     233048.970
4                             0                    27000.0     453919.455

   NAME_CONTRACT_STATUS_Demand  AMT_INST_MIN_REGULARITY
0                            0                 1700.325
1                            0                 2250.000
2                            0                 2250.000
3                            0                11795.760
4                            0                22924.890

[5 rows x 27 columns]
--------
Aggregated Features:
AMT_BALANCE_count
AMT_BALANCE_max
AMT_BALANCE_mean
AMT_BALANCE_median
AMT_BALANCE_min
AMT_BALANCE_sum
AMT_BALANCE_var
AMT_CREDIT_LIMIT_ACTUAL_count
AMT_CREDIT_LIMIT_ACTUAL_max
AMT_CREDIT_LIMIT_ACTUAL_mean
AMT_CREDIT_LIMIT_ACTUAL_median
AMT_CREDIT_LIMIT_ACTUAL_min
AMT_CREDIT_LIMIT_ACTUAL_sum
AMT_CREDIT_LIMIT_ACTUAL_var
AMT_DRAWINGS_ATM_CURRENT_count
AMT_DRAWINGS_ATM_CURRENT_max
AMT_DRAWINGS_ATM_CURRENT_mean
AMT_DRAWINGS_ATM_CURRENT_median
AMT_DRAWINGS_ATM_CURRENT_min
AMT_DRAWINGS_ATM_CURRENT_sum
AMT_DRAWINGS_ATM_CURRENT_var
AMT_DRAWINGS_CURRENT_count
AMT_DRAWINGS_CURRENT_max
AMT_DRAWINGS_CURRENT_mean
AMT_DRAWINGS_CURRENT_median
AMT_DRAWINGS_CURRENT_min
AMT_DRAWINGS_CURRENT_sum
AMT_DRAWINGS_CURRENT_var
AMT_DRAWINGS_OTHER_CURRENT_count
AMT_DRAWINGS_OTHER_CURRENT_max
AMT_DRAWINGS_OTHER_CURRENT_mean
AMT_DRAWINGS_OTHER_CURRENT_median
AMT_DRAWINGS_OTHER_CURRENT_min
AMT_DRAWINGS_OTHER_CURRENT_sum
AMT_DRAWINGS_OTHER_CURRENT_var
AMT_DRAWINGS_POS_CURRENT_count
AMT_DRAWINGS_POS_CURRENT_max
AMT_DRAWINGS_POS_CURRENT_mean
AMT_DRAWINGS_POS_CURRENT_median
AMT_DRAWINGS_POS_CURRENT_min
AMT_DRAWINGS_POS_CURRENT_sum
AMT_DRAWINGS_POS_CURRENT_var
AMT_INST_MIN_REGULARITY_count
AMT_INST_MIN_REGULARITY_max
AMT_INST_MIN_REGULARITY_mean
AMT_INST_MIN_REGULARITY_median
AMT_INST_MIN_REGULARITY_min
AMT_INST_MIN_REGULARITY_sum
AMT_INST_MIN_REGULARITY_var
AMT_PAYMENT_CURRENT_count
AMT_PAYMENT_CURRENT_max
AMT_PAYMENT_CURRENT_mean
AMT_PAYMENT_CURRENT_median
AMT_PAYMENT_CURRENT_min
AMT_PAYMENT_CURRENT_sum
AMT_PAYMENT_CURRENT_var
AMT_PAYMENT_TOTAL_CURRENT_count
AMT_PAYMENT_TOTAL_CURRENT_max
AMT_PAYMENT_TOTAL_CURRENT_mean
AMT_PAYMENT_TOTAL_CURRENT_median
AMT_PAYMENT_TOTAL_CURRENT_min
AMT_PAYMENT_TOTAL_CURRENT_sum
AMT_PAYMENT_TOTAL_CURRENT_var
AMT_RECEIVABLE_PRINCIPAL_count
AMT_RECEIVABLE_PRINCIPAL_max
AMT_RECEIVABLE_PRINCIPAL_mean
AMT_RECEIVABLE_PRINCIPAL_median
AMT_RECEIVABLE_PRINCIPAL_min
AMT_RECEIVABLE_PRINCIPAL_sum
AMT_RECEIVABLE_PRINCIPAL_var
AMT_RECIVABLE_count
AMT_RECIVABLE_max
AMT_RECIVABLE_mean
AMT_RECIVABLE_median
AMT_RECIVABLE_min
AMT_RECIVABLE_sum
AMT_RECIVABLE_var
AMT_TOTAL_RECEIVABLE_count
AMT_TOTAL_RECEIVABLE_max
AMT_TOTAL_RECEIVABLE_mean
AMT_TOTAL_RECEIVABLE_median
AMT_TOTAL_RECEIVABLE_min
AMT_TOTAL_RECEIVABLE_sum
AMT_TOTAL_RECEIVABLE_var
CNT_DRAWINGS_ATM_CURRENT_count
CNT_DRAWINGS_ATM_CURRENT_max
CNT_DRAWINGS_ATM_CURRENT_mean
CNT_DRAWINGS_ATM_CURRENT_median
CNT_DRAWINGS_ATM_CURRENT_min
CNT_DRAWINGS_ATM_CURRENT_sum
CNT_DRAWINGS_ATM_CURRENT_var
CNT_DRAWINGS_CURRENT_count
CNT_DRAWINGS_CURRENT_max
CNT_DRAWINGS_CURRENT_mean
CNT_DRAWINGS_CURRENT_median
CNT_DRAWINGS_CURRENT_min
CNT_DRAWINGS_CURRENT_sum
CNT_DRAWINGS_CURRENT_var
CNT_DRAWINGS_OTHER_CURRENT_count
CNT_DRAWINGS_OTHER_CURRENT_max
CNT_DRAWINGS_OTHER_CURRENT_mean
CNT_DRAWINGS_OTHER_CURRENT_median
CNT_DRAWINGS_OTHER_CURRENT_min
CNT_DRAWINGS_OTHER_CURRENT_sum
CNT_DRAWINGS_OTHER_CURRENT_var
CNT_DRAWINGS_POS_CURRENT_count
CNT_DRAWINGS_POS_CURRENT_max
CNT_DRAWINGS_POS_CURRENT_mean
CNT_DRAWINGS_POS_CURRENT_median
CNT_DRAWINGS_POS_CURRENT_min
CNT_DRAWINGS_POS_CURRENT_sum
CNT_DRAWINGS_POS_CURRENT_var
CNT_INSTALMENT_MATURE_CUM_count
CNT_INSTALMENT_MATURE_CUM_max
CNT_INSTALMENT_MATURE_CUM_mean
CNT_INSTALMENT_MATURE_CUM_median
CNT_INSTALMENT_MATURE_CUM_min
CNT_INSTALMENT_MATURE_CUM_sum
CNT_INSTALMENT_MATURE_CUM_var
MONTHS_BALANCE_count
MONTHS_BALANCE_max
MONTHS_BALANCE_mean
MONTHS_BALANCE_median
MONTHS_BALANCE_min
MONTHS_BALANCE_sum
MONTHS_BALANCE_var
NAME_CONTRACT_STATUS_Active_count
NAME_CONTRACT_STATUS_Active_max
NAME_CONTRACT_STATUS_Active_mean
NAME_CONTRACT_STATUS_Active_median
NAME_CONTRACT_STATUS_Active_min
NAME_CONTRACT_STATUS_Active_sum
NAME_CONTRACT_STATUS_Active_var
NAME_CONTRACT_STATUS_Approved_count
NAME_CONTRACT_STATUS_Approved_max
NAME_CONTRACT_STATUS_Approved_mean
NAME_CONTRACT_STATUS_Approved_median
NAME_CONTRACT_STATUS_Approved_min
NAME_CONTRACT_STATUS_Approved_sum
NAME_CONTRACT_STATUS_Approved_var
NAME_CONTRACT_STATUS_Completed_count
NAME_CONTRACT_STATUS_Completed_max
NAME_CONTRACT_STATUS_Completed_mean
NAME_CONTRACT_STATUS_Completed_median
NAME_CONTRACT_STATUS_Completed_min
NAME_CONTRACT_STATUS_Completed_sum
NAME_CONTRACT_STATUS_Completed_var
NAME_CONTRACT_STATUS_Demand_count
NAME_CONTRACT_STATUS_Demand_max
NAME_CONTRACT_STATUS_Demand_mean
NAME_CONTRACT_STATUS_Demand_median
NAME_CONTRACT_STATUS_Demand_min
NAME_CONTRACT_STATUS_Demand_sum
NAME_CONTRACT_STATUS_Demand_var
NAME_CONTRACT_STATUS_Refused_count
NAME_CONTRACT_STATUS_Refused_max
NAME_CONTRACT_STATUS_Refused_mean
NAME_CONTRACT_STATUS_Refused_median
NAME_CONTRACT_STATUS_Refused_min
NAME_CONTRACT_STATUS_Refused_sum
NAME_CONTRACT_STATUS_Refused_var
NAME_CONTRACT_STATUS_Sent proposal_count
NAME_CONTRACT_STATUS_Sent proposal_max
NAME_CONTRACT_STATUS_Sent proposal_mean
NAME_CONTRACT_STATUS_Sent proposal_median
NAME_CONTRACT_STATUS_Sent proposal_min
NAME_CONTRACT_STATUS_Sent proposal_sum
NAME_CONTRACT_STATUS_Sent proposal_var
NAME_CONTRACT_STATUS_Signed_count
NAME_CONTRACT_STATUS_Signed_max
NAME_CONTRACT_STATUS_Signed_mean
NAME_CONTRACT_STATUS_Signed_median
NAME_CONTRACT_STATUS_Signed_min
NAME_CONTRACT_STATUS_Signed_sum
NAME_CONTRACT_STATUS_Signed_var
SK_DPD_DEF_count
SK_DPD_DEF_max
SK_DPD_DEF_mean
SK_DPD_DEF_median
SK_DPD_DEF_min
SK_DPD_DEF_sum
SK_DPD_DEF_var
SK_DPD_count
SK_DPD_max
SK_DPD_mean
SK_DPD_median
SK_DPD_min
SK_DPD_sum
SK_DPD_var

Aggregated bureau:

                                          count          mean           std  \
NAME_CONTRACT_STATUS_Signed_mean       104307.0  3.631136e-03  3.180677e-02
NAME_CONTRACT_STATUS_Completed_median  104307.0  1.515718e-02  1.190990e-01
AMT_PAYMENT_CURRENT_var                 71922.0  2.343539e+09  1.062275e+10
NAME_CONTRACT_STATUS_Active_min        104307.0  8.277009e-01  3.776420e-01
SK_DPD_min                             104307.0  4.390885e-03  1.418106e+00
...                                         ...           ...           ...
AMT_DRAWINGS_ATM_CURRENT_median         72513.0  3.118773e+03  1.609790e+04
CNT_INSTALMENT_MATURE_CUM_median       104307.0  1.095425e+01  1.514720e+01
CNT_INSTALMENT_MATURE_CUM_var          103585.0  6.387927e+01  1.413354e+02
AMT_TOTAL_RECEIVABLE_count             104307.0  3.681739e+01  3.336264e+01
CNT_DRAWINGS_POS_CURRENT_count         104307.0  2.962885e+01  3.531603e+01

                                       min           25%           50%  \
NAME_CONTRACT_STATUS_Signed_mean       0.0  0.000000e+00  0.000000e+00
NAME_CONTRACT_STATUS_Completed_median  0.0  0.000000e+00  0.000000e+00
AMT_PAYMENT_CURRENT_var                0.0  2.537996e+07  1.603888e+08
NAME_CONTRACT_STATUS_Active_min        0.0  1.000000e+00  1.000000e+00
SK_DPD_min                             0.0  0.000000e+00  0.000000e+00
...                                    ...           ...           ...
AMT_DRAWINGS_ATM_CURRENT_median        0.0  0.000000e+00  0.000000e+00
CNT_INSTALMENT_MATURE_CUM_median       0.0  0.000000e+00  4.000000e+00
CNT_INSTALMENT_MATURE_CUM_var          0.0  0.000000e+00  5.673203e+00
AMT_TOTAL_RECEIVABLE_count             1.0  1.000000e+01  2.100000e+01
CNT_DRAWINGS_POS_CURRENT_count         0.0  0.000000e+00  1.200000e+01

                                                75%           max
NAME_CONTRACT_STATUS_Signed_mean       0.000000e+00  1.000000e+00
NAME_CONTRACT_STATUS_Completed_median  0.000000e+00  1.000000e+00
AMT_PAYMENT_CURRENT_var                9.787517e+08  9.697328e+11
NAME_CONTRACT_STATUS_Active_min        1.000000e+00  1.000000e+00
SK_DPD_min                             0.000000e+00  4.580000e+02
...                                             ...           ...
AMT_DRAWINGS_ATM_CURRENT_median        0.000000e+00  9.045000e+05
CNT_INSTALMENT_MATURE_CUM_median       1.600000e+01  7.550000e+01
CNT_INSTALMENT_MATURE_CUM_var          4.153923e+01  7.760000e+02
AMT_TOTAL_RECEIVABLE_count             7.400000e+01  9.600000e+01
CNT_DRAWINGS_POS_CURRENT_count         5.200000e+01  9.600000e+01

[189 rows x 8 columns]

### Datatypes for Credit Card Balance

In [13]:
df_ccb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB

### Describe the data

In [14]:
df_ccb.describe()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF
count,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,...,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,3.840312e+06,3.840312e+06
mean,1.904504e+06,2.783242e+05,-3.452192e+01,5.830016e+04,1.538080e+05,5.961325e+03,7.433388e+03,2.881696e+02,2.968805e+03,3.540204e+03,...,5.596588e+04,5.808881e+04,5.809829e+04,3.094490e-01,7.031439e-01,4.812496e-03,5.594791e-01,2.082508e+01,9.283667e+00,3.316220e-01
std,5.364695e+05,1.027045e+05,2.666775e+01,1.063070e+05,1.651457e+05,2.822569e+04,3.384608e+04,8.201989e+03,2.079689e+04,5.600154e+03,...,1.025336e+05,1.059654e+05,1.059718e+05,1.100401e+00,3.190347e+00,8.263861e-02,3.240649e+00,2.005149e+01,9.751570e+01,2.147923e+01
min,1.000018e+06,1.000060e+05,-9.600000e+01,-4.202502e+05,0.000000e+00,-6.827310e+03,-6.211620e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,-4.233058e+05,-4.202502e+05,-4.202502e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.434385e+06,1.895170e+05,-5.500000e+01,0.000000e+00,4.500000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00
50%,1.897122e+06,2.783960e+05,-2.800000e+01,0.000000e+00,1.125000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01,0.000000e+00,0.000000e+00
75%,2.369328e+06,3.675800e+05,-1.100000e+01,8.904669e+04,1.800000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.633911e+03,...,8.535924e+04,8.889949e+04,8.891451e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00
max,2.843496e+06,4.562500e+05,-1.000000e+00,1.505902e+06,1.350000e+06,2.115000e+06,2.287098e+06,1.529847e+06,2.239274e+06,2.028820e+05,...,1.472317e+06,1.493338e+06,1.493338e+06,5.100000e+01,1.650000e+02,1.200000e+01,1.650000e+02,1.200000e+02,3.260000e+03,3.260000e+03

### Missing Data for Credit Card Balance

In [15]:
missing_data(df_ccb)

                             Total    Percent
AMT_PAYMENT_CURRENT         767988  19.998063
AMT_DRAWINGS_ATM_CURRENT    749816  19.524872
CNT_DRAWINGS_POS_CURRENT    749816  19.524872
AMT_DRAWINGS_OTHER_CURRENT  749816  19.524872
AMT_DRAWINGS_POS_CURRENT    749816  19.524872
CNT_DRAWINGS_OTHER_CURRENT  749816  19.524872
CNT_DRAWINGS_ATM_CURRENT    749816  19.524872
CNT_INSTALMENT_MATURE_CUM   305236   7.948208
AMT_INST_MIN_REGULARITY     305236   7.948208
SK_ID_PREV                       0   0.000000
AMT_TOTAL_RECEIVABLE             0   0.000000
SK_DPD                           0   0.000000
NAME_CONTRACT_STATUS             0   0.000000
CNT_DRAWINGS_CURRENT             0   0.000000
AMT_PAYMENT_TOTAL_CURRENT        0   0.000000
AMT_RECIVABLE                    0   0.000000
AMT_RECEIVABLE_PRINCIPAL         0   0.000000
SK_ID_CURR                       0   0.000000
AMT_DRAWINGS_CURRENT             0   0.000000
AMT_CREDIT_LIMIT_ACTUAL          0   0.000000
AMT_BALANCE                      0   0.000000
MONTHS_BALANCE                   0   0.000000
SK_DPD_DEF                       0   0.000000

### Null values

### Summarized Dataset

In [16]:
df_ccb_summ.isna().sum()

SK_ID_PREV                          0
SK_ID_CURR                          0
CNT_DRAWINGS_CURRENT_min            0
CNT_DRAWINGS_CURRENT_max            0
CNT_DRAWINGS_CURRENT_count          0
                                 ...
AMT_INST_MIN_REGULARITY_count       0
AMT_INST_MIN_REGULARITY_sum         0
AMT_INST_MIN_REGULARITY_median      0
AMT_INST_MIN_REGULARITY_mean        0
AMT_INST_MIN_REGULARITY_var       722
Length: 191, dtype: int64

### Unsummarized Dataset

In [17]:
df_ccb.isna().sum()

SK_ID_PREV                         0
SK_ID_CURR                         0
MONTHS_BALANCE                     0
AMT_BALANCE                        0
AMT_CREDIT_LIMIT_ACTUAL            0
AMT_DRAWINGS_ATM_CURRENT      749816
AMT_DRAWINGS_CURRENT               0
AMT_DRAWINGS_OTHER_CURRENT    749816
AMT_DRAWINGS_POS_CURRENT      749816
AMT_INST_MIN_REGULARITY       305236
AMT_PAYMENT_CURRENT           767988
AMT_PAYMENT_TOTAL_CURRENT          0
AMT_RECEIVABLE_PRINCIPAL           0
AMT_RECIVABLE                      0
AMT_TOTAL_RECEIVABLE               0
CNT_DRAWINGS_ATM_CURRENT      749816
CNT_DRAWINGS_CURRENT               0
CNT_DRAWINGS_OTHER_CURRENT    749816
CNT_DRAWINGS_POS_CURRENT      749816
CNT_INSTALMENT_MATURE_CUM     305236
NAME_CONTRACT_STATUS               0
SK_DPD                             0
SK_DPD_DEF                         0
dtype: int64

## Drop all rows where target is NA from summarized table Train merged with Credit Card Balance

In [18]:
ccb_summ_na_target_dropped= df_summarized_joined_train_ccb.dropna(subset=['TARGET'])

### Join Unsummarized Credit Card Balance Dataset with Train and drop all rows with Target as na

In [19]:
df_joined_train_ccb_unsummarized = df_ccb.join(datasets['application_train'].set_index('SK_ID_CURR'), on='SK_ID_CURR')
df_joined_train_ccb_unsummarized_natarget_dropped = df_joined_train_ccb_unsummarized.dropna(subset=['TARGET'])

## 4) Correlation Analysis on summarized dataset

### Correlation on summarized table

In [20]:
ccb_summarized_corr = ccb_summ_na_target_dropped[ccb_summ_na_target_dropped.columns[:]].corr()['TARGET'].sort_values(ascending=False)
ccb_summarized_corr

TARGET                                 1.000000
CNT_DRAWINGS_ATM_CURRENT_mean          0.107908
CNT_DRAWINGS_CURRENT_max               0.100742
AMT_BALANCE_mean                       0.087098
AMT_TOTAL_RECEIVABLE_mean              0.086412
                                         ...
NAME_CONTRACT_STATUS_Refused_median         NaN
NAME_CONTRACT_STATUS_Demand_min             NaN
FLAG_MOBIL                                  NaN
FLAG_DOCUMENT_10                            NaN
FLAG_DOCUMENT_12                            NaN
Name: TARGET, Length: 296, dtype: float64

### Correlation on unsummarized table where all row with na balues for Target Dropped

In [21]:
ccb_unsummarized_corr = df_joined_train_ccb_unsummarized[df_joined_train_ccb_unsummarized.columns[:]].corr()['TARGET'].sort_values(ascending=False) 
ccb_unsummarized_corr

TARGET                         1.000000
DAYS_BIRTH                     0.059450
REGION_RATING_CLIENT_W_CITY    0.056224
REGION_RATING_CLIENT           0.053804
DAYS_LAST_PHONE_CHANGE         0.051437
                                 ...
EXT_SOURCE_1                  -0.138924
EXT_SOURCE_3                  -0.166260
FLAG_MOBIL                          NaN
FLAG_DOCUMENT_10                    NaN
FLAG_DOCUMENT_12                    NaN
Name: TARGET, Length: 127, dtype: float64

## Pipeline for Credit Card Balance

In [22]:
X = ccb_summ_na_target_dropped.loc[:, ccb_summ_na_target_dropped.columns != "TARGET"]
y = ccb_summ_na_target_dropped["TARGET"]

id_cols = ['SK_ID_CURR']
features = list(set(X.columns) - set(id_cols))
num_features = list(X[features].select_dtypes(include=['int64', 'float64']).columns)
cat_features = list(X[features].select_dtypes(include=['object', 'bool']).columns)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42, stratify=y)
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.15, random_state=42, stratify=y_train)
print(f"X train           shape: {X_train.shape}")
print(f"X validation      shape: {X_valid.shape}")
print(f"X test            shape: {X_test.shape}")

X train           shape: (63183, 311)
X validation      shape: (11151, 311)
X test            shape: (13118, 311)

In [ ]:
# run baseline model
from sklearn.metrics import accuracy_score, roc_auc_score

num_pipeline =Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    ('std_scaler', StandardScaler())
])

selected_features = (num_features) + (cat_features)

cat_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('ohe', OneHotEncoder(sparse=False, handle_unknown="ignore"))
    ])

data_pipeline = ColumnTransformer(transformers=[
        ("num_pipeline", num_pipeline, num_features),
        ("cat_pipeline", cat_pipeline, cat_features)],
        remainder='drop',
        n_jobs=-1
    )


full_pipeline_with_predictor = Pipeline([
        ("preparation", data_pipeline),
        ('select', SelectKBest()),
        ("linear", LogisticRegression())
    ])

param_grid = {
    'linear__penalty':[#'l1', 'l2', 'elasticnet',
                                 'none'],
    #,'linear__C':[1.0#, 10.0, 100.0]
    'select__k':[7, #15, 20, 30, 50, 100
                ]
}

gd1 = GridSearchCV(full_pipeline_with_predictor, param_grid= param_grid, cv = 3, scoring='roc_auc')

model = gd1.fit(X_train, y_train)


try:
    expLog
except NameError:
    expLog = pd.DataFrame(columns=["exp_name", 
                                   "Train Acc", 
                                   "Valid Acc",
                                   "Test  Acc",
                                   "Train AUC", 
                                   "Valid AUC",
                                   "Test  AUC"
                                  ])

exp_name = f"Baseline_{len(selected_features)}_features"
expLog.loc[len(expLog)] = [f"{exp_name}"] + list(np.round(
               [accuracy_score(y_train, model.predict(X_train)), 
                accuracy_score(y_valid, model.predict(X_valid)),
                accuracy_score(y_test, model.predict(X_test)),
                roc_auc_score(y_train, model.predict_proba(X_train)[:, 1]),
                roc_auc_score(y_valid, model.predict_proba(X_valid)[:, 1]),
                roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])],
    4)) 

expLog